name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests on Python 3.12
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          echo "torch==2.9.0" > constraints.txt
          pip install "torch==2.9.0" --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
          pip install -e .[test] -c constraints.txt

    - name: Run tests
      run: |
        pytest -q

